// Generated by LiveScript 1.3.1
(function(){
  var ref$, map, fold1, keys, values, first, flatten, h, net, Backbone, subscriptionMan, UdpGun, os, util, Console;
  ref$ = require('prelude-ls'), map = ref$.map, fold1 = ref$.fold1, keys = ref$.keys, values = ref$.values, first = ref$.first, flatten = ref$.flatten;
  h = require('helpers');
  net = require('net');
  Backbone = require('backbone4000');
  subscriptionMan = require('subscriptionman2');
  UdpGun = require('udp-client');
  os = require('os');
  util = require('util');
  h.extendm(exports, require('./index'));
  Console = exports.Console = Backbone.Model.extend4000({
    name: 'console',
    initialize: function(){
      return this.startTime = process.hrtime()[0];
    },
    parseTags: function(tags){
      return keys(
      tags);
    },
    log: function(logEvent){
      var hrtime, tags;
      hrtime = new Date().getTime();
      tags = this.parseTags(logEvent.tags);
      return console.log((hrtime[0] - this.startTime) + "." + hrtime[1]);
    }
  }) + "\t " + tags.join(', ') + "\t" + (logEvent.msg || "-");
}).call(this);
