// Generated by LiveScript 1.3.1
(function(){
  exports.child = function(test){
    var logger, l, child, ret;
    logger = require('./index.js');
    l = new logger.Logger({
      context: {
        tags: ['bla']
      }
    });
    child = l.child(logger.Data({}, ['more', 'tags']));
    ret = child.log(logger.Data("test msg", {
      some: 'data'
    }, 'some', 'tags'));
    console.log("RETURN", ret);
    return test.done();
  };
}).call(this);
